# ワークフロー名：GitHub Actionsの実行履歴に表示される名前
name: Fetch and Merge Kanpo RSS Data

# 実行トリガー：いつこのワークフローを実行するか
on:
  # メインブランチ（mainまたはmaster）にプッシュがあった時
  push:
    branches:
      - main
      - master
  
  # スケジュール実行：毎日午前0時 (UTC) に自動で実行
  schedule:
    - cron: '0 0 * * *' 

# 実行するジョブ（処理のまとまり）
jobs:
  build:
    # 実行環境：Ubuntuの最新バージョン
    runs-on: ubuntu-latest

    # 実行ステップ
    steps:
    
    # 1. リポジトリのチェックアウト（コードの取得）
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Python環境のセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. 必要なライブラリのインストール
    - name: Install dependencies
      run: |
        # feedparserはRSSを読み込むために必要
        pip install feedparser
        
    # 4. データディレクトリの作成（もし存在しなければ）
    - name: Create data directory
      run: |
        mkdir -p data

    # 5. Pythonスクリプトの実行（データ取得とマージ）
    - name: Run Python script
      run: python fetch_rss.py
      
    # 6. 変更されたファイルのコミットとプッシュ
    # このステップで kanpo_feed.json の変更をリポジトリに反映させる
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # 変更があったJSONファイルのみを対象とする
        file_pattern: 'data/kanpo_feed.json'
        commit_message: "Auto: Update kanpo-rss data with new entries"
